### ISSUE TITLE
No Server Error

### ISSUE THREAD

**Issue by UnInfamous** [zhliau/fika-spt-server-docker#1]
Hey, thank you kindly for putting a SPT/FIKA package together!

I have Docker running on my Unraid server.
Created an image from scratch to test out (along with updated Tarkov and a fresh install of SPT on my machine), but unfortunately I'm running into the following:
"No server available at: 'SPT' to conect to"

The container is using a bridge network (i.e. bridging 172.17.0.2:6969/TCP to 10.10.1.2:6969). Upon changing the launcher settings and connecting, it immediately presents the error.
No logs from the server that it ever connects (everything looks good that the server is running), or anything from the Docker/Unraid logs.

Tried the following to troubleshoot to no avail:
- Restarted the container
- Restarted SPT.Launcher.exe on my machine
- Tried wiping the image and appdata, and trying again
- I am able to connect to my local SPT.Server.exe (obviously when settings are changed)
- I am successful in connecting to, but not launching the game when using [stblog/spt-server](https://hub.docker.com/r/stblog/spt-server), so it doesn't seem to be a networking issue

Here is my Docker run template through Unraid:
![image](https://github.com/user-attachments/assets/278bf2f1-b246-468f-805f-4c2b40d071e0)

**Comment by zhliau** [comment]
Thanks for trying out this image!

I'm not familiar with Unraid, but I'm assuming that the `SPT Port` section is specifying the port forwarding rule for 6969, so that part looks good.
Are you running this server using existing server files, or is this fully from scratch?
What is the SPT server URL you are specifying in the launcher?

**Comment by UnInfamous** [comment]
My pleasure, I appreciate that it optionally comes with FIKA.

Unraid for Docker is mainly just a GUI.

Fully from scratch on both the server and the client side.

http://10.10.1.2:6969
![image](https://github.com/user-attachments/assets/bbb5c1a4-2184-4ecd-a197-e587f3cb10f8)

Just tried running the image locally to the same affect (http://localhost:6969):
![image](https://github.com/user-attachments/assets/142ef5cb-f43b-48b1-a1db-73130aca5b07)

**Comment by zhliau** [comment]
Interesting that it says it's listening on 127.0.0.1. The loopback interface in the container is different from the host's. Can you verify your `SPT_Data/Server/configs/http.json` looks like this? 

```
{
    "ip": "0.0.0.0",
    "port": 6969,
    "backendIp": "0.0.0.0",
    "backendPort": 6969,
    "webSocketPingDelayMs": 90000,
    "logRequests": true,
    "serverImagePathOverride": {}
}

```

**Comment by robpneu** [comment]
@zhliau what do you think about having entrypoint.sh do this done automatically? Or an option to do this automatically? I had this same issue since I have multiple networks specified in my compose file (default and my reverse proxy) and found the same solution.
